---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 9/19/2023 3:45 PM
---

-- Lua FLVSS widget

local function create()
  local sensor = system.getSource("LiPo")
  local mah = system.getSource("mAh")
  local capacity = 5000
  local cellCount = 6
  return {sensor=sensor, value=nil, mah = mah, capacity=capacity, cellCount=cellCount}
end

local function paint(widget)
  if widget.sensor ~= nil then
    lcd.font(FONT_L)
    local y = 10
    lcd.drawText(10, y, "Total = " .. widget.sensor:stringValue() .. " (" .. widget.sensor:stringValue(OPTION_CELL_COUNT) .. " cells)")
    y = y + 30
    for i = 1, widget.sensor:value(OPTION_CELL_COUNT) do
      lcd.drawText(10, y, "Cell[" .. i .."] = " .. widget.sensor:stringValue(OPTION_CELL_INDEX(i)))
      y = y + 30
    end
	local mahValue = widget.mah:rawValue()
    mahValue = "mAh = " .. mahValue
    lcd.drawText(10, y, mahValue,0)
  end
end

local function wakeup(widget)
  local newValue = nil
  if widget.sensor == nil then
    widget.sensor = system.getSource("LiPo")
  end
  if widget.sensor ~= nil then
    newValue = widget.sensor:stringValue()
  end
  if widget.value ~= newValue then
    widget.value = newValue
    lcd.invalidate()
  end
  lcd.invalidate()
end

local function configure(widget)

    -- Trigger switch position
    line = form.addLine("flvss")
    form.addSwitchField(line, form.getFieldSlots(line)[0], function() return widget.triggerswitch end, function(value) widget.triggerswitch = value end)

    -- Battery pack capacity
    line = form.addLine("Capacity")
    local capacity = form.addNumberField(line, nil,100, 10000, function() return widget.capacity end, function(value) widget.capacity = value end)
    capacity:suffix("mAh")
	capacity:default(5000)
	capacity:step(100)

    -- Battery pack capacity
    line = form.addLine("Cell Count")
    local capacity = form.addNumberField(line, nil,1, 12, function() return widget.cellCount end, function(value) widget.cellCount = value end)
	capacity:default(6)
	capacity:step(1)

    line = form.addLine("Play Sounds")
    form.addBooleanField(line, form.getFieldSlots(line)[0], function() return widget.soundmode end, function(value) widget.soundmode = value end)

end

local function read(widget)
        widget.capacity = storage.read("capacity")
        widget.cellCount = storage.read("cellCount")
        widget.soundmode = storage.read("soundmode")
end

local function write(widget)
        storage.write("capacity",widget.capacity)
        storage.write("cellCount",widget.cellCount)
        storage.write("preset",widget.preset)
        storage.write("soundmode",widget.soundmode)
end


local function init()
  system.registerWidget({key="flvss", name="Lua Flvss", create=create, paint=paint, wakeup=wakeup, configure=configure, read=read, write=write, persistent=true})
end

return {init=init}
